export const cartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    DECREASE_ITEM_COUNT_BY_ONE: 'DECREASE_ITEM_COUNT_BY_ONE'
}